version: '3'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortener-server
    container_name: urlshortener-server
    volumes:
      - ./db.gob:/go/src/urlshortener/db.gob
      - ./src/server/UI:/go/src/urlshortener/server/UI
    networks:
      - urlshortener

  nginx:
    image: nginx:1.16.0
    container_name: urlshortener-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhosts:/etc/nginx/vhosts.d
    networks:
      - urlshortener
      - nginxnet
    depends_on:
      - go
      - wordpress

  mysqldb:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: deathly
      MYSQL_DATABASE: wordpress
      MYSQL_USER: skings
      MYSQL_PASSWORD: mysqlishere
    networks:
      - urlshortener

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysqldb:3306
      WORDPRESS_DB_USER: skings
      WORDPRESS_DB_PASSWORD: mysqlishere
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mysqldb
    networks:
      - urlshortener
    volumes:
      - ./wordpress/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./wordpress/plugins:/var/www/html/wp-content/plugins


networks:
  urlshortener:
    driver: bridge
  nginxnet:
    external:
      name: nginxnet
volumes:
  db_data: {}