version: '3'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortener-server
    container_name: urlshortener-server
    volumes:
      - ./src/server/UI:/go/bin/UI
      - ./db.gob:/go/bin/db.gob
    networks:
      - urlshortener

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: urlshortener-nginx
    container_name: urlshortener-nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - urlshortener

networks:
  urlshortener:
    driver: bridge