version: '3'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortener-server
    container_name: urlshortener-server
    volumes:
      - ./db.gob:/go/src/urlshortener/db.gob
      - ./src/server/UI:/go/src/urlshortener/server/UI
    networks:
      - urlshortener

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: urlshortener-nginx
    container_name: urlshortener-nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - urlshortener
      - nginxnet

networks:
  urlshortener:
    driver: bridge
  nginxnet:
    external:
      name: nginxnet
